version: "3.3"
services: 
  web:
    depends_on: 
      - mysql
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: django-k8s:v0.0.2
    environment:
      - PORT=8020
    env_file:
      - web/.env
    ports:
      - "8020:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh" 
  mysql:
    image: mysql:oracle
    volumes:
      - ./public:/public
    env_file:
      - web/.env


