version: "3.3"
services: 
  nginx:
    build: 
      context: ./web/nginx 
      dockerfile: Dockerfile
    image: django-nginx-k8s:v0.0.1
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    depends_on: 
      - mysql
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: django-app-k8s:v0.0.1
    environment:
      - PORT=8000
    env_file:
      - web/.env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
  mysql:
    image: mysql:oracle
    volumes:
      - ./public:/public
    env_file:
      - web/.env

volumes:
  static_volume:


