apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-fss-app
spec:
 storageClassName: oci-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: 10.0.10.254            # Mount private ip
  path: "/FileSystemApp"         # File system export path
  readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-fss-nginx
spec:
 storageClassName: oci-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: 10.0.10.254              # Mount private ip
  path: "/FileSystemNGINX"         # File system export path
  readOnly: false