apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: grzegorz.wysopal@oracle.com
    privateKeySecretRef:
      name: tls-secret-key
    solvers:
    - http01:
        ingress:
          class: nginx
        