apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: default
spec:
  dnsNames:
    - test.ocitestdomain.co.uk
  secretName: tls-secret-key
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer