apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-fss
provisioner: oracle.com/oci-fss
parameters:
  mntTargetId: ocid1.mounttarget.oc1.uk_london_1.aaaaacvippx2taaqnruhellqojxwiotvnmwwy33omrxw4ljrfvqwiljr
